apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-prometheus-k8ssandra
  labels:
{{ include "k8ssandra-cluster.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-prometheus-k8ssandra
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-prometheus-k8ssandra
