apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: {{ .Release.Name }}-prometheus-k8ssandra
