---
apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ .Release.Name }}-grafana-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
spec:
  ingress:
    enabled: false
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: false
    log:
      level: warn
      mode: console
    security:
      admin_password: {{ .Values.monitoring.grafana.security.adminPassword }}
      admin_user: {{ .Values.monitoring.grafana.security.adminUser }}
{{- if .Values.monitoring.grafana.config.server }}
    server:
{{- if not (empty .Values.monitoring.grafana.config.server.rootUrl) }}
      root_url: {{ .Values.monitoring.grafana.config.server.rootUrl }}
{{- end }}
{{- if and (not (empty .Values.monitoring.grafana.config.server.rootUrl)) .Values.monitoring.grafana.config.server.serveFromSubPath }}
      serve_from_sub_path: true
{{- end }}
{{- end }}
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
