{{- if .Values.backupRestore.medusa.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-medusa-operator-k8ssandra
  labels:
{{ include "k8ssandra.labels" . | indent 4 }}
{{- end }}
